---
- name: Converge
  hosts: all
  become: true
  vars:
    drupal_log_path: /var/log/vhosts/account/project/drupal.log
    drupal_syslog_read_users:
      - johndoe
  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Creates directory
      file:
        path: /var/log/vhosts/account/project
        state: directory

    - name: Ansible create file if it doesn't exist
      file:
        path: "/var/log/vhosts/account/project/drupal.log"
        state: touch

  roles:
    - role: ansible-role-drupal-syslog
