---
- name: Verify role
  hosts: all
  become: yes

  vars:
    drupal_log_path: /var/log/vhosts/account/project/drupal.log
    drupal_syslog_read_users:
      - johndoe

  tasks:
    - name: Obtain the ACL for drupal log
      acl:
        path: "{{ drupal_log_path }}"
      register: acl_info

    - debug: var=acl_info

